version: '3.8'

services:
  caddy:
    image: jjhughes57/caddy-local
    container_name: caddy
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CF_API_TOKEN=foobar

volumes:
  caddy_data:
  caddy_config: